adds testing
rvtr/rvtrx-campground pull request #133
Opened 2020-10-30 13:54 UTC by Jonny-Code

2020-10-30 21:42 UTC, escalonn requested changes

2020-10-30 21:42 UTC, escalonn commented on angular/src/app/modules/account/account/account.component.spec.ts
> +  const toastrServiceStub = jasmine.createSpyObj('toastrServiceStub', ['error']);
that's not what this first argument is for

(this file's comments also apply to the other 2 similar changesets)

2020-10-30 21:42 UTC, escalonn commented on angular/src/app/modules/account/account/account.component.spec.ts
> +  toastrServiceSpy = toastrServiceStub.error.and.returnValue(of(''));
that's not an error, [`throw`](https://www.learnrxjs.io/learn-rxjs/operators/creation/throw) is probably the right replacement for `of`

2020-10-30 21:42 UTC, escalonn commented on angular/src/app/modules/account/account/account.component.ts
> +  callAccountGet(editingService: GenericEditingService<Partial<Account>>): void {
revert this

2020-10-30 21:42 UTC, escalonn commented on angular/src/app/modules/account/account/account.component.ts
> +import { toastrError } from '../../../utils/toastr/toastrError';
make a toast service and encapsulate the ngx-toastr details and this util function in it.

2020-10-30 21:42 UTC, escalonn commented on angular/src/app/modules/lodging/lodging-details/lodging-details.component.spec.ts
> +    expect(message.valid).toBeTrue();
ideally one behavior gets one spec, but it's borderline

2020-11-04 21:05 UTC, markmoorerev approved these changes

2020-11-04 21:17 UTC, escalonn requested changes

2020-11-04 21:17 UTC, escalonn commented on angular/src/app/modules/account/account/account.component.spec.ts
> +    toastServiceSpy.toastError.calls.reset();
no... this is supposed to be a test of the component, but the component plays no role in what you've written here. you're just testing stubs against stubs.

the _test_ shouldn't be calling the `get`. the component is already calling the `get`. your job is to provide an object to the component which will throwError when someone calls `get` on it, in this test. in the other test, it should provide an actual good result.

2021-02-24 21:59 UTC, fredbelotte commented
inactive

2021-02-24 21:59 UTC, closed without merging